//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperTech_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientPackage()
        {
            this.PackageInstances = new HashSet<PackageInstance>();
        }
    
        public int SaleID { get; set; }
        public int PackageID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual ServicePackage ServicePackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageInstance> PackageInstances { get; set; }
    }
}
