//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperTech_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSchedule
    {
        public int EmployeeID { get; set; }
        public int TimeID { get; set; }
        public int DateID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> BookingID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ScheduleStatu ScheduleStatu { get; set; }
    }
}
