//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperTech_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageInstance
    {
        public int InstanceID { get; set; }
        public int SaleID { get; set; }
        public int PackageID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual BookingLine BookingLine { get; set; }
        public virtual ClientPackage ClientPackage { get; set; }
        public virtual InstanceStatu InstanceStatu { get; set; }
    }
}
